# Generated by Django 4.1.7 on 2023-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_services_icon_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.FileField(default='', max_length=255, upload_to='icon', verbose_name='Иконка услуги'),
        ),
    ]
