# Generated by Django 4.1.7 on 2023-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='clip', verbose_name='Образец письма'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='icon', verbose_name='Иконка услуги'),
        ),
    ]
